### ISSUE TITLE
请问这个脚本怎么使用呀

### ISSUE THREAD

**Issue by sudongyuer** [liulinboyi/HTMLParser#1]
请大佬告知，xw:sudongyuer

**Comment by liulinboyi** [comment]
> 请大佬告知，xw:sudongyuer

你好，非常感谢你的问题，其实，最好去使用这个库，https://www.npmjs.com/package/htmlparser2 这个库更稳定，本仓库是一个实验性质的项目，没有经过长期的用户使用反馈。

**Comment by liulinboyi** [comment]
> 请大佬告知，xw:sudongyuer

如果你想学习怎么写HTMLParser，可以去这个库 https://github.com/liulinboyi/simple-htmlparser 看看，这里有一个极简的HTMLParser，还有HTML AST（抽象语法树）到HTML文本的还原。

https://github.com/liulinboyi/simple-htmlparser
简单的HTMLparser和AST还原到HTML
